import type { Metadata } from 'next';
import { Outfit } from 'next/font/google';
import './globals.css';

const inter = Outfit({ subsets: ['latin'], weight: ['400', '700'] });

export const metadata: Metadata = {
	title: 'Qr-component',
	description: 'Generated by create qr component',
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang='en'>
			<body className={inter.className}>
				<main className='container'>{children}</main>
			</body>
		</html>
	);
}
